// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
	UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (User, error)
}

var _ Querier = (*Queries)(nil)
