// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions
    (wallet_id, amount, type, status, transfer_id, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, wallet_id, amount, type, status, transfer_id, created_at, description
`

type CreateTransactionParams struct {
	WalletID    pgtype.UUID       `json:"wallet_id"`
	Amount      int64             `json:"amount"`
	Type        TransactionType   `json:"type"`
	Status      TransactionStatus `json:"status"`
	TransferID  pgtype.UUID       `json:"transfer_id"`
	Description pgtype.Text       `json:"description"`
}

type CreateTransactionRow struct {
	ID          pgtype.UUID        `json:"id"`
	WalletID    pgtype.UUID        `json:"wallet_id"`
	Amount      int64              `json:"amount"`
	Type        TransactionType    `json:"type"`
	Status      TransactionStatus  `json:"status"`
	TransferID  pgtype.UUID        `json:"transfer_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (CreateTransactionRow, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WalletID,
		arg.Amount,
		arg.Type,
		arg.Status,
		arg.TransferID,
		arg.Description,
	)
	var i CreateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.TransferID,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT id, wallet_id, amount, type, status, description, transfer_id, created_at, updated_at, deleted_at
FROM transactions
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) GetTransactionById(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.TransferID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByTransferId = `-- name: GetTransactionByTransferId :one
SELECT id, wallet_id, amount, type, status, description, transfer_id, created_at, updated_at, deleted_at
FROM transactions
WHERE transfer_id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) GetTransactionByTransferId(ctx context.Context, transferID pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByTransferId, transferID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.TransferID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionsByWalletId = `-- name: GetTransactionsByWalletId :many
SELECT id, wallet_id, amount, type, status, description, transfer_id, created_at, updated_at, deleted_at
FROM transactions
WHERE wallet_id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) GetTransactionsByWalletId(ctx context.Context, walletID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByWalletId, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Amount,
			&i.Type,
			&i.Status,
			&i.Description,
			&i.TransferID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status = $2
WHERE id = $1
RETURNING id, wallet_id, amount, type, status, description, transfer_id, created_at, updated_at, deleted_at
`

type UpdateTransactionStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status TransactionStatus `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.ID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.TransferID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
