// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToBalance = `-- name: AddToBalance :one
UPDATE wallets
SET balance = balance + $2
WHERE user_id = $1
  AND deleted_at IS NULL
RETURNING id, user_id, balance, created_at, updated_at, deleted_at
`

type AddToBalanceParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) AddToBalance(ctx context.Context, arg AddToBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, addToBalance, arg.UserID, arg.Balance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (id, user_id, balance, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, balance, created_at
`

type CreateWalletParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CreateWalletRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Balance   int64              `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (CreateWalletRow, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.ID,
		arg.UserID,
		arg.Balance,
		arg.CreatedAt,
	)
	var i CreateWalletRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const deductFromBalance = `-- name: DeductFromBalance :one
UPDATE wallets
SET balance = balance - $2
WHERE user_id = $1
  AND deleted_at IS NULL
RETURNING id, user_id, balance, created_at, updated_at, deleted_at
`

type DeductFromBalanceParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Balance int64       `json:"balance"`
}

func (q *Queries) DeductFromBalance(ctx context.Context, arg DeductFromBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, deductFromBalance, arg.UserID, arg.Balance)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWalletById = `-- name: GetWalletById :one
SELECT id, user_id, balance, created_at, updated_at, deleted_at
FROM wallets
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetWalletById(ctx context.Context, id pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletById, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWalletByUserId = `-- name: GetWalletByUserId :one
SELECT id, user_id, balance, created_at, updated_at, deleted_at
FROM wallets
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetWalletByUserId(ctx context.Context, userID pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUserId, userID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
